chimas/members/urls.py
from django.urls import path, include
from django.core import signing

from .views import (
    get_sign_up_view, sign_up_view, gsu_don_view, sign_in_view, logout_view,
)
from .account_views import (
    dashboard_index, dependants_index_view, dependant_detail_view,
    dependants_claims_view, claims_index_view, subscription_view,
    providers_index_view, city_providers_index_view, benefits_index_view,
    complains_index_view, complain_detail_view, create_complain_view, cancel_membership_view,
)

app_name = 'members'

deps_urls = [
    path('', dependants_index_view, name='deps_index'),
    path('claims/', dependants_claims_view, name='deps_claims_index'),
    path('<int:pk>/', dependant_detail_view, name='dep_detail'),
]

claims_urls = [
    path('', claims_index_view, name='claims_index'),
]

account_urls = [
    path('', dashboard_index, name='index'),
    path('benefits/', benefits_index_view, name='benefits_index'),
    path('claims/', include(claims_urls), ),
    path('dependants/', include(deps_urls, )),
]

providers_urls = [
    path('', providers_index_view, name='providers_index'),
    path('<int:pk>/', city_providers_index_view, name='city_providers'),
]

complaint_urls = [
    path('', complains_index_view, name='complaints_index'),
    path('<int:pk>/', complain_detail_view, name='complaint_detail'),
    path('create/', create_complain_view, name='create_complaint'),
]

urlpatterns = [
    path('', include(account_urls)),
    path('sign-up/', get_sign_up_view, name='sign_up_url'),
    path('sign-up-request-sent/', gsu_don_view, name='gsu_done'),
    path('sign-up/<str:member>/', sign_up_view, name='sign_up'),
    path('sign-in/', sign_in_view, name='sign_in'),
    path('sign-out/', logout_view, name='logout'),
    path('subscription/', subscription_view, name='subscription'),
    path('providers/', include(providers_urls)),
    path('complaints/', include(complaint_urls)),
    path('cancel-membership/', cancel_membership_view, name="cancel_membership")
]

chimas/news/urls.py
from django.urls import path, include

from .views import (
    news_index_view, article_detail_view,
)

urlpatterns = [
    path('', news_index_view, name='news_index'),
    path('<int:pk>/', article_detail_view, name='article'),
]

chimas/users/urls.py
from django.urls import path

from chimas.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

app_name = 'root'

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="index"),
    path("news/", include('chimas.news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chimas/members/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db.models import F
from django.core import signing
from django.utils.translation import ugettext_lazy as _

from django_hosts.resolvers import reverse_lazy

from chimas.core.models import UUIDModel, gen_member_number

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)


def get_current_year():
    return timezone.now().year


class Member(UUIDModel):
    MARRIED = 'M'
    SINGLE = 'S'
    DIVORCED = 'D'
    WIDOWED = 'W'
    MARITAL_STATUSES = (
        (MARRIED, "Married"),
        (SINGLE, 'Single'),
        (DIVORCED, 'Divorced'),
        (WIDOWED, 'Widowed'),
    )
    STATUSES = (
        ('A', 'Active'),
        ('S', 'Suspended'),
        ('C', 'Cancelled'),
    )
    membership_status = models.CharField(
        choices=STATUSES, default='A', max_length=1,
    )
    plan = models.ForeignKey(
        'plans.Plan', on_delete=models.CASCADE, related_name='members',
    )
    member_number = models.CharField(default=gen_member_number, max_length=30, unique=True, editable=False)
    date_joined = models.DateField(
        verbose_name=_("Date joined"),
        help_text=_("Date when member signed up for plan."), auto_now_add=True,
    )
    name = models.CharField(
        max_length=255,
    )
    dob = models.DateField()
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=1,
    )
    marital_status = models.CharField(
        verbose_name=_("Marital status"), max_length=1,
        choices=MARITAL_STATUSES, default=MARRIED, help_text=_("Member's marital status.")
    )
    national_id = models.CharField(
        max_length=12,
    )
    address = models.TextField()
    phone = models.CharField(max_length=255, )
    email_address = models.EmailField(null=True, blank=True, unique=True)

    # Next Of Kin
    nok_name = models.CharField(
        max_length=255,
    )
    nok_phone = models.CharField(
        max_length=255,
    )

    allergies = models.TextField(
        null=True, blank=True,
    )

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='member'
    )

    class Meta:
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return f'{self.name} ({self.national_id})'

    @property
    def is_active(self):
        return self.membership_status == 'A'

    def get_sign_up_url(self):
        return reverse_lazy(
            viewname='members:sign_up',
            kwargs={'member': signing.dumps({'pk': self.pk}, key=settings.CHIMAS_KEY)},
            host='members',
        )

    @property
    def age(self):
        today = timezone.now().date()
        age = today.year - self.dob.year - \
              ((today.month, today.day) < (self.dob.month, self.dob.day))
        return age

    age.fget.short_description = _("Age")

    def subscription(self):
        qs = self.subscriptions.filter(
            start__lte=timezone.now().date(), end__gte=timezone.now().date()
        )
        try:
            return qs.get()
        except:
            print("Found more than one subscription")
            return None

    @property
    def is_subscribed(self):
        if self.subscription():
            return True
        return False

    @property
    def nok(self):
        return f'{self.nok_name}, {self.nok_phone}'


class Dependant(UUIDModel):
    CHILD = "C"
    SPOUSE = "S"
    OTHER = "O"
    RELATIONSHIP_CHOICES = (
        (CHILD, "Child"),
        (SPOUSE, "Spouse"),
        (OTHER, "Other"),
    )

    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='dependants')
    relationship = models.CharField(
        verbose_name=_("Relationship"), max_length=1,
        choices=RELATIONSHIP_CHOICES, help_text=_("Relationship to plan registrant.")
    )
    relationship_description = models.TextField(
        verbose_name=_("Relationship description"), null=True, blank=True,
        help_text=_("If relationship is indicated as other, please explain relationship to dependant here.")
    )
    name = models.CharField(
        max_length=255,
    )
    dob = models.DateField()
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=1,
    )
    national_id = models.CharField(
        max_length=12,
    )
    phone = models.CharField(
        null=True, blank=True, max_length=255,
    )
    allergies = models.TextField(
        null=True, blank=True,
    )

    class Meta:
        verbose_name = 'dependant'
        verbose_name_plural = 'dependants'

    @property
    def number(self):
        return self.id

    def __str__(self):
        return self.name

    @property
    def age(self):
        today = timezone.now().date()
        age = today.year - self.dob.year - \
              ((today.month, today.day) < (self.dob.month, self.dob.day))
        return age

    age.fget.short_description = _("Age")

    @property
    def address(self):
        return self.member.address

    def clean(self):
        if not self.pk:
            # Validate dependant count
            if self.member.plan is None:
                raise ValidationError(
                    _("%(member)s has not been registered for a plan yet."),
                    params={
                        'member': self.member.name,
                    }
                )
            else:
                plan = self.member.plan
                if self.member.dependants.count() + 1 > plan.max_dependants:
                    raise ValidationError(
                        _("You can only have %(dependants)s dependants under the %(policy)s plan."),
                        params={
                            'dependants': plan.max_dependants,
                            'policy': plan.name.title(),
                        }
                    )
            super(Dependant, self).clean()

        if self.relationship == "O" and (self.relationship_description is None or self.relationship_description == ""):
            raise ValidationError(
                {'relationship_description': _("Explain the dependant's relationship with the plan registrant."), }
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


class Subscription(UUIDModel):
    member = models.ForeignKey(
        'Member', on_delete=models.CASCADE, related_name='subscriptions'
    )
    year = models.PositiveIntegerField(
        default=get_current_year
    )
    paid_on = models.DateField()
    amount_paid = models.DecimalField(
        decimal_places=2, max_digits=19,
    )
    balance = models.DecimalField(
        decimal_places=2, max_digits=19, default=0
    )
    payment_reference = models.CharField(
        max_length=255,
    )
    start = models.DateField()
    end = models.DateField()

    class Meta:
        verbose_name = 'plan subscription'
        verbose_name_plural = 'plan subscriptions'
        unique_together = (
            'member', 'year',
        )

    def __str__(self):
        return f'{self.member.name} ({self.year})'

    def save(self, *args, **kwargs):
        self.full_clean()

        is_update = False
        if self.pk:
            is_update = True

        super().save(*args, **kwargs)

        if not is_update:  # Will only run when subscription touches db for the 1st time
            # Add member benefits for period
            plan_benefits = self.member.plan.benefits.all()

            for benefit in plan_benefits:
                self.member.benefits.create(
                    subscription=self,
                    category=benefit.category,
                    balance=benefit.value,
                )

            # Add dependant benefit for period
            for dependant in self.member.dependants.all():
                for benefit in plan_benefits:
                    dependant.benefits.create(
                        subscription=self,
                        category=benefit.category,
                        balance=benefit.value,
                    )

    @property
    def expired(self):
        return self.start < timezone.now().date() and self.end < timezone.now().date()


class MemberBenefit(UUIDModel):
    member = models.ForeignKey(
        'Member', on_delete=models.CASCADE, related_name='benefits',
    )
    subscription = models.ForeignKey(
        'Subscription', on_delete=models.CASCADE, related_name='member_benefits'
    )
    category = models.ForeignKey(
        'core.MedicalCategory', on_delete=models.CASCADE,
    )
    balance = models.DecimalField(
        max_digits=19, decimal_places=2,
    )

    class Meta:
        verbose_name = 'member benefit'
        verbose_name_plural = 'member benefits'
        unique_together = ('member', 'category', 'subscription')

    def __str__(self):
        return f'{self.category.name} ({self.balance})'


class MemberClaim(UUIDModel):
    provider = models.ForeignKey(
        'providers.Provider', on_delete=models.CASCADE, related_name="member_claims"
    )
    member = models.ForeignKey(
        'Member', on_delete=models.CASCADE, related_name='claims'
    )
    benefit = models.ForeignKey(
        'MemberBenefit', on_delete=models.CASCADE, related_name='claims',
    )
    value = models.DecimalField(
        decimal_places=2, max_digits=19,
    )
    notes = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'member claim'
        verbose_name_plural = 'member claims'
        ordering = ('-created',)

    def __str__(self):
        return f'{self.member.name}, {self.benefit.category.name}'

    def clean(self):
        if self.benefit.subscription.expired:
            raise ValidationError('Cannot make claim on expired subscription')

        if self.benefit and self.value:
            if self.pk:

chimas/complaints/views.py
from django.shortcuts import render

# Create your views here.

chimas/core/views.py
from django.shortcuts import render
from django.views import generic

chimas/members/views.py
from django.shortcuts import render
from django.views import View, generic
from django.contrib.auth import get_user_model, views as auth_views
from django.core import signing
from django.conf import settings
from django.http import HttpResponseForbidden, Http404, HttpResponseRedirect

from django_hosts.resolvers import reverse_lazy

from chimas.members.models import Member
from chimas.core.utils import send_mail

from .forms import GetSignUpForm, SignUpForm, AuthenticationForm

User = get_user_model()


class GetSignUp(generic.FormView):
    template_name = 'members/auth/get_link.html'
    form_class = GetSignUpForm

    def form_valid(self, form):
        member = form.get_member()
        send_mail(
            "Create CHIMAS Account",
            member.email_address,
            'members/auth/reg.txt',
            html=None,
            context={'member': member}
        )
        return super(GetSignUp, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            viewname='members:gsu_done',
            host='members'
        )


get_sign_up_view = GetSignUp.as_view()


class GSUDone(generic.TemplateView):
    template_name = 'members/auth/email_sent.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # ctx.update({'email': })
        return ctx


gsu_don_view = GSUDone.as_view()


class SignUpView(generic.CreateView):
    template_name = 'members/auth/sign_up.html'
    form_class = SignUpForm

    def __init__(self):
        self.member = None
        super(SignUpView, self).__init__()

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(member=self.member, **self.get_form_kwargs())

    def dispatch(self, request, *args, **kwargs):
        try:
            value = signing.loads(kwargs.get('member'), key=settings.CHIMAS_KEY)
        except signing.BadSignature:
            return HttpResponseForbidden("Failed to verify sign up url")
        else:
            try:
                self.member = Member.objects.get(pk=value.get('pk', None))
            except Member.DoesNotExist:
                return Http404("Could not find member record!")
            else:
                if self.member.user:
                    return HttpResponseForbidden('Member has already signed up')
                return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super(SignUpView, self).get_initial()
        initial.update({
            'username': self.member.member_number,
        })
        return initial

    def form_valid(self, form):
        user = form.save()
        self.member.user = user
        self.member.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy(
            viewname='members:sign_in',
            host='members',
        )


sign_up_view = SignUpView.as_view()


class SignInView(auth_views.LoginView):
    template_name = 'members/auth/sign_in.html'
    authentication_form = AuthenticationForm

    def get_success_url(self):
        return reverse_lazy(
            viewname='members:index',
            host='members',
        )


sign_in_view = SignInView.as_view()


class LogoutView(auth_views.LogoutView):
    next_page = reverse_lazy(
        viewname='members:sign_in',
        host='members'
    )


logout_view = LogoutView.as_view()

chimas/plans/views.py
from django.shortcuts import render

# Create your views here.

chimas/templates/members/dashboard/dependants/claims.html
{% extends 'members/base.html' %}
{% load static hosts %}
{% block claims_lnk %}active{% endblock %}
{% block page_css %}
    <link rel="stylesheet" href="{% static 'assets/examples/css/pages/profile.css' %}">
{% endblock %}
{% block header_title %}
    Claims by Dependants
{% endblock %}
{% block page_title %}
    Claims by Dependants
{% endblock %}
{% block site_content %}
    <div class="row">
        <div class="col-md-6">
            <div class="widget">
                <header class="widget-header"><h4 class="widget-title">Claims</h4></header>
                <hr class="widget-separator">
                <div class="widget-body">
                    <div class="streamline ml-4">
                        {% for claim in claims %}
                            <div class="sl-item pb-3">
                                <div class="sl-content ml-3">
                                    <h5 class="m-t-0">
                                        <a href="javascript:void(0)" class="mr-1 theme-color">
                                            <i class="fa fa-hospital-o"></i> {{ claim.provider }}
                                        </a>
                                        <small class="text-muted fz-sm">
                                            {{ claim.provider.city|default:'' }}
                                        </small>
                                    </h5>
                                    <p>
                                    <dl>
                                        <dt>Amount</dt>
                                        <dd class="lead">${{ claim.value }}</dd>
                                        <dt>Category (Balance)</dt>
                                        <dd class="lead">
                                            {{ claim.benefit.category.name }} (${{ claim.benefit.balance }})
                                        </dd>
                                        <dt>Address</dt>
                                        <dd class="lead">{{ claim.provider.address }}</dd>
                                        <dt>Date</dt>
                                        <dd class="lead">{{ claim.created|date }}</dd>
                                        <dt>Subscription</dt>
                                        <dd class="lead">
                                            {% with claim.benefit.subscription as sub %}
                                                {{ sub.year }}
                                                <strong>({{ sub.start|date:'M d' }} - {{ sub.end|date:'M d' }})</strong>
                                            {% endwith %}
                                        </dd>
                                    </dl>
                                </div>
                            </div><!-- /.sl-item -->
                        {% endfor %}
                    </div><!-- /.streamline -->
                </div><!-- /.widget-body -->
            </div><!-- /.widget -->
        </div>
    </div>
{% endblock %}

chimas/templates/members/dashboard/dependants/detail.html
{% extends 'members/base.html' %}
{% load static hosts %}
{% block page_css %}
    <link rel="stylesheet" href="{% static 'assets/examples/css/pages/profile.css' %}">
{% endblock %}
{% block header_title %}
    {{ dep }}
{% endblock %}
{% block page_title %}
    {{ dep }}
{% endblock %}
{% block site_content %}
    <div class="profile-header">
        <div class="profile-header-cover">
            <div class="text-center">
                <h5 class="mb-1">
                    <a href="javascript:void(0)">#{{ dep.pk }}</a>
                </h5>
                <h2 class="mb-4">
                    <a href="javascript:void(0)">{{ dep.name }}</a>
                </h2>
                <dl class="dl-horizontal">
                    <dt>Benefactor</dt>
                    <dd class="lead">{{ dep.member.name }}</dd>
                    <dt>Relationship</dt>
                    <dd class="lead">{{ dep.get_relationship_display }}</dd>
                    <dt>Gender, Age</dt>
                    <dd class="lead">{{ dep.get_gender_display }}, {{ dep.age }}</dd>
                    <dt>National ID</dt>
                    <dd class="lead">{{ dep.national_id }}</dd>
                    <dt>Phone</dt>
                    <dd class="lead">{{ dep.phone|default_if_none:'-' }}</dd>
                    <dt>Address</dt>
                    <dd class="lead">{{ dep.address }}</dd>
                    <dt>Allergies</dt>
                    <dd class="lead">{{ dep.allergies }}</dd>
                </dl>

            </div>
        </div><!-- ./profile-header-cover -->
    </div>
{% endblock %}

chimas/templates/members/dashboard/dependants/index.html
{% extends 'members/base.html' %}
{% load static hosts %}
{% block header_title %}
    Dependants
{% endblock %}
{% block deps_lnk %}
    active
{% endblock %}
{% block page_title %}
    Dependants
{% endblock %}
{% block site_content %}
    <div class="row">
        {% for dep in deps %}
            <div class="col-lg-3 col-sm-6">
                <div class="card bg-white">
                    <div class="card-block text-center">
                        <a href="{% host_url 'members:dep_detail' dep.pk host 'members' %}">
                            <h6 class="lead">{{ dep.name }}</h6>
                        </a>
                        <div class="mb-3">{{ dep.get_relationship_display }}</div>
                        <div>
                            <a href="javascript:void(0)" class="social-icon text-hv-facebook">
                                {{ dep.get_gender_display }}, {{ dep.age }}
                            </a>
                        </div>
                    </div><!-- /.card-block -->
                </div><!-- /.card -->
            </div><!-- /.col -->
        {% endfor %}
    </div>
{% endblock %}